# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'general.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PIL import Image

class Ui_MainWindow1(object):
    def setup_general(self, MainWindow):
        MainWindow.setObjectName("General")
        self.im = Image.open('label_general.png')
        width, height = self.im.size
        MainWindow.resize(width, height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_general = QtWidgets.QLabel(self.centralwidget)
        self.label_general.setObjectName("label_general")
        self.gridLayout.addWidget(self.label_general, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_general.setStyleSheet("background-image : url(label_general.png)")
        self.retranslate_ui1(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui1(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "General"))
        self.label_general.setText(_translate("MainWindow", "TextLabel"))

    def setup_generator(self, MainWindow):
        MainWindow.setObjectName("Generator")
        self.im = Image.open('label_generator.png')
        width, height = self.im.size
        MainWindow.resize(width, height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_general = QtWidgets.QLabel(self.centralwidget)
        self.label_general.setObjectName("label_general")
        self.gridLayout.addWidget(self.label_general, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_general.setStyleSheet("background-image : url(label_generator.png)")
        self.retranslate_ui2(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui2(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Generator"))
        self.label_general.setText(_translate("MainWindow", "TextLabel"))

    def setup_headpond(self, MainWindow):
        MainWindow.setObjectName("General")
        self.im = Image.open('label_generator.png')
        width, height = self.im.size
        MainWindow.resize(width, height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_general = QtWidgets.QLabel(self.centralwidget)
        self.label_general.setObjectName("label_general")
        self.gridLayout.addWidget(self.label_general, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_general.setStyleSheet("background-image : url(label_generator.png)")
        self.retranslate_ui3(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui3(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Headpond"))
        self.label_general.setText(_translate("MainWindow", "TextLabel"))

    def setup_other(self, MainWindow):
        MainWindow.setObjectName("General")
        self.im = Image.open('label_generator.png')
        width, height = self.im.size
        MainWindow.resize(width, height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_general = QtWidgets.QLabel(self.centralwidget)
        self.label_general.setObjectName("label_general")
        self.gridLayout.addWidget(self.label_general, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_general.setStyleSheet("background-image : url(label_generator.png)")
        self.retranslate_ui4(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui4(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Others"))
        self.label_general.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setup_general(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
